# Env mode (local, production, development)
env: local

# Connection string to PostgreSQL db
pg_connection_string: 'postgres://postgres:password@localhost/dbname'

# Server address
address: 'localhost:3000'
